### ISSUE TITLE
Replace title on README file

### ISSUE THREAD

**Issue by joanapires1** [diverintech/python-projects#6]
On README.dm file, the point 5 should be Quiz Game instead of Calculator Program.

Repo: https://github.com/diverintech/python-projects/blob/main/README.md

**Comment by diverintech** [comment]
Fixed: https://github.com/diverintech/python-projects/pull/5/commits/18e8063296f16761091fdd1ba904c906302041c3

**Comment by diverintech** [comment]
Fixed: https://github.com/diverintech/python-projects/pull/5/commits/18e8063296f16761091fdd1ba904c906302041c3
